"""empty message

Revision ID: 45bc1a9a0d8b
Revises:
Create Date: 2022-06-23 16:42:10.771707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "45bc1a9a0d8b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currency_pairs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("currency_code_one", sa.String(length=3), nullable=False),
        sa.Column("currency_code_two", sa.String(length=3), nullable=False),
        sa.CheckConstraint("char_length(currency_code_one) = 3"),
        sa.CheckConstraint("char_length(currency_code_two) = 3"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("currency_code_one", "currency_code_two"),
    )
    op.create_index(op.f("ix_currency_pair_id"), "currency_pairs", ["id"], unique=False)
    op.create_index(op.f("ix_currency_pairs_currency_code_one"), "currency_pairs", ["currency_code_one"], unique=False)
    op.create_index(op.f("ix_currency_pairs_currency_code_two"), "currency_pairs", ["currency_code_two"], unique=False)
    op.create_table(
        "exchange_rates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("currency_pair_id", sa.Integer(), nullable=False),
        sa.Column("rate_date", sa.Date(), nullable=False),
        sa.Column("rate", sa.Numeric(scale=4), nullable=False),
        sa.ForeignKeyConstraint(
            ["currency_pair_id"],
            ["currency_pairs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rate_date", "currency_pair_id"),
    )
    op.create_index(op.f("ix_exchange_rates_rate_date"), "exchange_rates", ["rate_date"], unique=False)
    op.create_index(op.f("ix_exchange_rates_id"), "exchange_rates", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_exchange_rates_id"), table_name="exchange_rates")
    op.drop_index(op.f("ix_exchange_rates_rate_date"), table_name="exchange_rates")
    op.drop_table("exchange_rates")
    op.drop_index(op.f("ix_currency_pairs_currency_code_two"), table_name="currency_pairs")
    op.drop_index(op.f("ix_currency_pairs_currency_code_one"), table_name="currency_pairs")
    op.drop_index(op.f("ix_currency_pair_id"), table_name="currency_pairs")
    op.drop_table("currency_pairs")
    # ### end Alembic commands ###
